# Generated by Django 4.2.7 on 2025-08-10 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('context_type', models.CharField(choices=[('GENERAL', 'General'), ('CHAPTER', 'Chapter'), ('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment')], default='GENERAL', max_length=50)),
                ('context_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI conversation',
                'verbose_name_plural': 'AI conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('suggested_questions', models.JSONField()),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'quiz suggestion',
                'verbose_name_plural': 'quiz suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrammarCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('corrected_text', models.TextField()),
                ('suggestions', models.JSONField(default=list)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grammar check',
                'verbose_name_plural': 'grammar checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('USER', 'User'), ('AI', 'AI Assistant'), ('SYSTEM', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aiconversation')),
            ],
            options={
                'verbose_name': 'AI message',
                'verbose_name_plural': 'AI messages',
                'ordering': ['created_at'],
            },
        ),
    ]
