# Generated by Django 4.2.7 on 2025-08-10 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('MATHEMATICS', 'Mathematics'), ('SCIENCE', 'Science'), ('ENGLISH', 'English'), ('HISTORY', 'History'), ('GEOGRAPHY', 'Geography'), ('LITERATURE', 'Literature'), ('COMPUTER_SCIENCE', 'Computer Science'), ('ART', 'Art'), ('MUSIC', 'Music'), ('PHYSICAL_EDUCATION', 'Physical Education'), ('OTHER', 'Other')], max_length=30)),
                ('language', models.CharField(choices=[('EN', 'English'), ('UR', 'Urdu'), ('AR', 'Arabic'), ('FR', 'French'), ('ES', 'Spanish'), ('DE', 'German'), ('ZH', 'Chinese'), ('OT', 'Other')], default='EN', max_length=2)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('description', models.TextField()),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('INSTITUTE', 'Institute Only')], default='PUBLIC', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_books', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='institutes.institute')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
                'ordering': ['order'],
                'unique_together': {('book', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('completed_sections', models.JSONField(default=list)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='books.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reading progress',
                'verbose_name_plural': 'reading progress',
                'unique_together': {('user', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='ChapterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INTRODUCTION', 'Introduction'), ('SUMMARY', 'Summary'), ('SLOS', 'Student Learning Objectives'), ('PRE_READING', 'Pre-Reading Activities'), ('VOCABULARY_TRANSLATION', 'Vocabulary & Translation'), ('GLOSSARY', 'Glossary'), ('SHORT_QUESTIONS', 'Short Questions'), ('OBJECTIVE_QUESTIONS', 'Objective Questions'), ('VOCAB_GRAMMAR', 'Vocabulary & Grammar'), ('ORAL_COMMUNICATION', 'Oral Communication'), ('WRITING_SKILLS', 'Writing Skills'), ('IDIOMS_PHRASALS', 'Idioms & Phrasal Verbs'), ('ASSESSMENT_TEST', 'Assessment Test')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.JSONField()),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='books.chapter')),
            ],
            options={
                'verbose_name': 'chapter section',
                'verbose_name_plural': 'chapter sections',
                'ordering': ['order'],
                'unique_together': {('chapter', 'kind', 'order')},
            },
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_tags', to='books.book')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_tags', to='books.tag')),
            ],
            options={
                'unique_together': {('book', 'tag')},
            },
        ),
    ]
