# Generated by Django 4.2.7 on 2025-08-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptersection',
            name='kind',
            field=models.CharField(choices=[('INTRODUCTION', 'Introduction'), ('POINT_WISE_SUMMARY', 'Point-wise Summary'), ('SLOS', 'Student Learning Objectives'), ('PRE_READING_QUESTIONS', 'Pre-reading Questions'), ('VOCABULARY_TEXT_TRANSLATION', 'Vocabulary, Text & Translation'), ('GLOSSARY', 'Glossary'), ('EXERCISE_SHORT_QUESTIONS', 'Exercise: Short Questions'), ('EXERCISE_OBJECTIVES', 'Exercise: Objectives'), ('EXERCISE_VOCABULARY_GRAMMAR', 'Exercise: Vocabulary and Grammar'), ('EXERCISE_ORAL_COMMUNICATION', 'Exercise: Oral Communication'), ('EXERCISE_WRITING_SKILLS', 'Exercise: Writing Skills'), ('IDIOMS_PHRASAL_VERBS', 'Idioms and Phrasal Verbs of the Lesson'), ('ASSESSMENT_TEST', 'Assessment Test')], max_length=30),
        ),
    ]
