# Generated by Django 4.2.7 on 2025-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_chaptersection_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptersection',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='chapter_sections/pdfs/'),
        ),
    ]
